name: IaC - Terraform AWS Deploy

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Ação do Terraform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform-deploy:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "sa-east-1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform ${{ github.event.inputs.action }}
        working-directory: terraform
        run: terraform ${{ github.event.inputs.action }} -auto-approve
